# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('theatre_name', models.CharField(max_length=100)),
                ('row_name', models.CharField(max_length=1)),
                ('number_of_seats', models.IntegerField()),
                ('aisle_seats', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Movie Detail',
                'verbose_name_plural': 'Movie Details',
                'ordering': ['id'],
            },
        ),
    ]
