# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-13 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181013_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='seatInfo',
            field=models.CharField(default='adsd', max_length=1000),
            preserve_default=False,
        ),
    ]
